CREATE TABLE comarcas (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
	oab	VARCHAR(100) NULL,
	oabuf VARCHAR(2) NULL,
	cpf	VARCHAR(11) NULL,
	name VARCHAR(200) NULL,
	phone VARCHAR(11) NULL,
	cellphone VARCHAR(11) NULL,
	email VARCHAR(200) NULL,
) ENGINE = innodb

