CREATE TABLE comarcas (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
	oab	VARCHAR(100) NOT NULL,
	oabuf VARCHAR(2) NOT NULL,
	cpf	VARCHAR(11) NOT NULL,
	name VARCHAR(200) NOT NULL,
	phone VARCHAR(11) NULL,
	cellphone VARCHAR(11) NULL,
	email VARCHAR(200) NULL,
) ENGINE = innodb

